<a href="https://colab.research.google.com/github/PatchavaKoushikChowdary/Day-1-assessment-python/blob/main/pytorch_fundamentals_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [7]:
scalar=torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
scalar.ndim

0

In [8]:
vector=torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [9]:
vector.shape

torch.Size([2])

In [14]:
MATRIX=torch.tensor([[7,8], [9,8]])
print(MATRIX)

tensor([[7, 8],
        [9, 8]])


In [11]:
TENSOR=torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
print(TENSOR)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [12]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
random_tensor=torch.rand(10,10)
print(random_tensor)

tensor([[0.3158, 0.7831, 0.4247, 0.1338, 0.6015, 0.1128, 0.1066, 0.7738, 0.3853,
         0.0977],
        [0.2886, 0.5103, 0.0916, 0.6120, 0.2599, 0.6964, 0.8524, 0.0062, 0.8216,
         0.2463],
        [0.9138, 0.5178, 0.4059, 0.5906, 0.7096, 0.4647, 0.5704, 0.2295, 0.8292,
         0.0495],
        [0.2224, 0.9271, 0.8130, 0.0324, 0.9711, 0.4992, 0.5602, 0.0238, 0.5709,
         0.3911],
        [0.5737, 0.8180, 0.7600, 0.5345, 0.6113, 0.6176, 0.9969, 0.9371, 0.3743,
         0.0440],
        [0.9452, 0.4741, 0.8134, 0.3040, 0.8659, 0.8977, 0.5445, 0.3792, 0.0201,
         0.4549],
        [0.0828, 0.3512, 0.5294, 0.4424, 0.3770, 0.9057, 0.0710, 0.6291, 0.2595,
         0.4507],
        [0.0928, 0.7116, 0.1678, 0.2467, 0.9523, 0.0636, 0.9701, 0.2574, 0.0107,
         0.5462],
        [0.2392, 0.9041, 0.7430, 0.2533, 0.6621, 0.0058, 0.4227, 0.4153, 0.0180,
         0.2722],
        [0.9351, 0.1499, 0.8371, 0.1561, 0.6285, 0.1457, 0.2451, 0.6943, 0.6127,
         0.6112]])


In [18]:
random_tensor.ndim

2

In [19]:
r=torch.rand(size=(224,224,3))
print(r.shape)
print(r.ndim)

torch.Size([224, 224, 3])
3


In [20]:
tensor=torch.tensor([1,2,3])
print(tensor)

tensor([1, 2, 3])


In [21]:
x=torch.arange(0,100,10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [22]:
x.argmin()

tensor(0)

In [23]:
x.argmax()

tensor(9)

In [24]:
x[0],x[9]

(tensor(0), tensor(90))

In [31]:
import torch
x = torch.arange(1.,10.)
print(x,x.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [32]:
x_reshaped=x.reshape(1,9)
print(x_reshaped,x_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [33]:
z=x.view(1,9)
print(z,z.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [34]:
z[:,0]=5
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [35]:
x_stacked=torch.stack([x,x,x,x])
print(x_stacked)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [36]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
x_original = torch.rand(size=(224,224,3))
x_permuted=x_original.permute(2,0,1)
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [39]:
x_original[0,0,0]=728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [41]:
x=torch.arange(1,10).reshape(1,3,3)
print(x,x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [42]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [43]:
x[0][0]

tensor([1, 2, 3])

In [44]:
x[0][0][0]

tensor(1)

In [45]:
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
print(array,tensor)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [46]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
print(tensor,numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]


In [47]:
torch.rand(3,3)

tensor([[0.3492, 0.0830, 0.2132],
        [0.2747, 0.0012, 0.7977],
        [0.0260, 0.5992, 0.7301]])

In [48]:
a=torch.rand(3,4)
b=torch.rand(3,4)
print(a)
print(b)
print(a==b)

tensor([[0.8070, 0.3826, 0.7940, 0.5296],
        [0.2418, 0.5723, 0.6202, 0.4126],
        [0.6810, 0.8167, 0.0143, 0.9899]])
tensor([[0.3493, 0.0381, 0.0876, 0.0092],
        [0.4357, 0.8511, 0.7999, 0.4342],
        [0.8134, 0.1875, 0.0591, 0.2832]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
